---
title: 'Regression Models'
author: '`r if(knitr::is_html_output()) {"&#x1f468;&#x1F3FB;&#x200d;&#x1f4bb; Anderson H Uyekita"} else {NULL}`'
output:
  github_document: default
params:
  author: 'Anderson H Uyekita'
  course: 'Regression Models'
  course_url: 'https://www.coursera.org/learn/regression-models'
  specialization: 'Data Science: Foundations using R Specialization'
  specialization_url: 'https://www.coursera.org/specializations/data-science-foundations-r'
  instructor: 'Brian Caffo'
  course_start: !r lubridate::ymd('2022/07/05', tz = 'America/Sao_Paulo')
  course_finish: !r lubridate::today(tzone = "America/Sao_Paulo")
  certificate_url: './'
---

```{r setup,include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, message = FALSE, warning = FALSE)
library(rmarkdown)
library(lubridate)
```

`r if(!knitr::is_html_output()) {sprintf(fmt = "* &#x1f468;&#x1F3FB;&#x200d;&#x1f4bb; Author: %s", params$author)}`
`r sprintf(fmt = "* &#x1f4da; Specialization: [%s](%s){target='_blank' rel='noopener'}", params$specialization, params$specialization_url)`
`r sprintf(fmt = "* &#x1f4d6; Course: [%s](%s){target='_blank' rel='noopener'}", params$course, params$course_url)`
    `r sprintf(fmt = "* &#x1F9D1;&#x200d;&#x1F3EB; Instructor: %s", params$instructor)`
    `r sprintf(fmt = "* &#x1F6A6; Start: %s", format(params$course_start, "%A, %d %B %Y"))`
    `r sprintf(fmt = "* &#x1F3C1; Finish: %s", format(params$course_finish, "%A, %d %B %Y"))`
`r if(params$certificate_url != "./") {sprintf(fmt = "* &#x1F393; [Certificate](%s)", params$certificate_url)}`

--------------------------------------------------------------------------------

#### Assignments & Deliverables

* [&#x1F680; Course Project 1 Repository](https://github.com/AndersonUyekita/regression-models_course-project)
* [&#x1F4DD; Quiz 1](./Week 1/quiz-1_regression-models.md)
* [&#x1F4DD; Quiz 2](./Week 2/quiz-2_regression-models.md)
* [&#x1F4DD; Quiz 3](./Week 3/quiz-3_regression-models.md)
* [&#x1F4DD; Quiz 4](./Week 4/quiz-4_regression-models.md)

#### Class Notes

* [&#x1F4C6; Week 1](./Week 1)
* [&#x1F4C6; Week 2](./Week 2)
* [&#x1F4C6; Week 3](./Week 3)
* [&#x1F4C6; Week 4](./Week 4)
* [&#x1F4D1; Course Textbook Notes](./book)

#### Course Description

> Linear models, as their name implies, relates an outcome to a set of predictors of interest using linear assumptions.  Regression models, a subset of linear models, are the most important statistical analysis tool in a data scientist’s toolkit. This course covers regression analysis, least squares and inference using regression models. Special cases of the regression model, ANOVA and ANCOVA will be covered as well. Analysis of residuals and variability will be investigated. The course will cover modern thinking on model selection and novel uses of regression models including scatterplot smoothing.


#### Course Syllabus

> This class has three main components
> 
> * Least squares and linear regression
> * Multivariable regression
> * Generalized linear models  
> 
> The full list of topics are as follows:

* Module 1 -- Least Squares and Linear Regression
    * 01_01 Introduction
    * 01_02 Notation
    * 01_03 Ordinary least squares
    * 01_04 Regression to the mean
    * 01_05 Linear regression
    * 01_06 Residuals
    * 01_07 Regression inference
* Module 2 -- Linear Regression & Multivariable Regression
    * 02_01 Multivariate regression
    * 02_02 Multivariate examples
    * 02_03 Adjustment
    * 02_04 Residual variation and diagnostics
    * 02_05 Multiple variables
* Module 3 -- Multivariable Regression, Residuals, & Diagnostics
    * 03_01 GLMs
    * 03_02 Binary outcomes
    * 03_03 Count outcomes
    * 03_04 Olio
* Module 4 -- Logistic Regression and Poisson Regression
    * Logistic Regression
    * Poisson Regression
    * Hodgepodge

#### Course Textbook

The book [&#x1F4D4; Regression Models for Data Science in R](./book/regression-models-for-data-science-in-r.pdf) covers the lecture material in this course.

#### Course Projects

> The Course Project is an opportunity to demonstrate the skills you have learned during the course. It is graded through peer assessment. You must earn a grade of at least 80% to pass the peer assessment.