---
title: '`Week 4` Regression Models'
author: '`r if(knitr::is_html_output()) {"&#x1f468;&#x1F3FB;&#x200d;&#x1f4bb; Anderson H Uyekita"} else {NULL}`'
output:
  github_document: default
params:
  author: 'Anderson H Uyekita'
  course: 'Regression Models'
  course_url: 'https://www.coursera.org/learn/regression-models'
  specialization: 'Data Science: Foundations using R Specialization'
  specialization_url: 'https://www.coursera.org/specializations/data-science-foundations-r'
  instructor: 'Brian Caffo'
  course_start: !r lubridate::ymd('2022/07/05', tz = 'America/Sao_Paulo')
  course_finish: !r lubridate::today(tzone = "America/Sao_Paulo")
  week: ' Week 4'
---

```{r setup,include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, message = FALSE, warning = FALSE)
library(rmarkdown)
library(lubridate)
```

`r if(!knitr::is_html_output()) {sprintf(fmt = "* &#x1f468;&#x1F3FB;&#x200d;&#x1f4bb; Author: %s", params$author)}`
`r sprintf(fmt = "* &#x1f4da; Specialization: [%s](%s){target='_blank' rel='noopener'}", params$specialization, params$specialization_url)`
`r sprintf(fmt = "* &#x1f4d6; Course: [%s](%s){target='_blank' rel='noopener'}", params$course, params$course_url)`
    `r sprintf(fmt = "* &#x1F9D1;&#x200d;&#x1F3EB; Instructor: %s", params$instructor)`
`r sprintf(fmt = "* &#x1F4C6; %s", params$week)`
    `r sprintf(fmt = "* &#x1F6A6; Start: %s", format(params$course_start, "%A, %d %B %Y"))`
    `r sprintf(fmt = "* &#x1F3C1; Finish: %s", format(params$course_finish, "%A, %d %B %Y"))`

--------------------------------------------------------------------------------

#### Assignments & Deliverables

* [&#x1F680; Course Project 4 Repository](https://github.com/AndersonUyekita/regression-models_course-project-4)
* [&#x1F4DD; Quiz 4](./quiz-4_regression-models.md)

#### Slides

* Module 4 -- Logistic Regression and Poisson Regression
    * Logistic Regression
    * Poisson Regression
    * Hodgepodge

#### Description

> This week, we will work on generalized linear models, including binary outcomes and Poisson regression.

--------------------------------------------------------------------------------

## Class Notes

### Generalized linear models (GLMs)

>The generalized linear model is family of models that includes linear models. By extending the family, it handles many of the issues with linear models, **but at the expense of some complexity and loss of some of the mathematical tidiness**. A GLM involves three components
>
> * An exponential family model for the response.
> * A systematic component via a linear predictor.
> * A link function that connects the means of the response to the linear predictor.
>
> The three most famous cases of GLMs are:

* linear models, binomial and
* binary regression and Poisson regression.

>We’ll go through the GLM model specification and likelihood for all three. For linear models, we’ve developed them previously.
>
>The next two modules will be devoted to binomial and Poisson regression. We’ll only focus on the most popular and useful link functions.

### Logistic regression

>Binary GLMs come from trying to model outcomes **that can take only two values**.
>
>Some examples include: survival or not
>
>At the end of a study, winning versus losing of a team and success versus failure of a treatment or product. Often these outcomes are called Bernoulli outcomes, from the Bernoulli distribution named after the famous probabilist and mathematician.
>
>If we happen to have several exchangeable binary outcomes for the same level of covariate values, then that is binomial data and we can aggregate the 0’s and 1’s into the count of 1’s. As an example, imagine if we sprayed insect pests with 4 different pesticides and counted whether they died or not. Then for each spray, we could summarize the data with the count of dead and total number that were sprayed and treat the data as binomial rather than Bernoulli.
















### Poisson Regression

>Many data take the form of unbounded count data. For example, consider the number of calls to a call center or the number of flu cases in an area or the number of hits to a web site.
>
>In some cases the counts are clearly bounded. However, modeling the counts as unbounded is often done when the upper limit is not known or very large relative to the number of events.
>
>If the upper bound is known, the techniques we’re discussing can be used to model the proportion or rate. The starting point for most count analysis is the the Poisson distribution.
>
>In the following lectures, we go over some of the basics of modeling count data.



### Mishmash

> This lecture is a bit of an mishmash of interesting things that one can accomplish with linear models.

